### ISSUE TITLE
Upgrade React Table to V8

### ISSUE THREAD

**Issue by NoopDog** [clevercanary/data-browser#392]
#### Need 
React table V8 has been released https://github.com/TanStack/table this is a complete rewrite in TypeScript that also has some breaking changes in the API. This also has some features that make client-side facet search easier!  We want to upgrade but also want to understand first the changes that this will require in the codebase. 

#### Approach

- [ ] Review the v8 documentation and current v7 implementation and explore on a branch what it will take to upgrade.
- [ ] Create/Present an upgrade plan 
- [ ] Upgrade once the upgrade plan is approved and scheduled.

**Comment by BruceRodrigues** [comment]
### Where React table is currently used

- `@types/react-table-config.d.ts`
Used to redeclare react-table's module. 
This module was declared to react-table v7 play well with typescript.

- `app/apis/azul/common/fileTransformer.ts`
Just import react-table's `FilterValue` type.

- `app/components/Table/functions.ts`
Just import react-table's `ColumnInstace` type.

- `app/components/TableCreator/tableCreator.tsx`
Import react-table's `CellProps` and `Column` types, and create the column configuration used by the react-table's hook and the cell component.

- `app/components/Table/table.tsx`
Uses react-table's hooks to create a table component. 
This file uses the API to create a controlled and uncontrolled table.
Also, uses the sort and pagination plugins.

### Upgrade approach

- `@types/react-table-config.d.ts` might not be needed anymore, since v8 fully supports typescript. We can try to delete this file.
- Create `ColumnDefs` (v8) is basically the same as creating `Columns` (v7). Just need to adjust some properties' names.
- The sorting function will need changes, since now sort handlers are passed as hook's options, instead of being called by component's `onClick`. However, this shouldn't be difficult. v8 Still supports `manual sorting`, which we use to create an uncontrolled table.
- Similarly to sorting, pagination will also require some changes. Since the handler functions are passed as hook's options, instead of being called by component's `onClick`. Pagination still has the `manual pagination` option, which we currently use to create an uncontrolled table.
- Rendering the table on v8 is basically the same as v7. Iterating over the headers and calling the render cell function. Might be necessary just to change the called function's names.


### Conclusion
- Upgrade to react's table v8 is not difficult. I didn't find any feature that we currently use that is not supported by the new version. We'll need to change the properties' names for the table config and adjust the handlers for sorting and paging.

**Comment by NoopDog** [comment]
@BruceRodrigues thanks for the detailed review. Let's go ahead and implement the V8 upgrade! Thanks. D
